server:
  port: 9090
  servlet:
    context-path: /api
    multipart:
      max-file-size: 10mb
      max-request-size: 10mb
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

logging.level.web: DEBUG